version: '3'
services:
  # links to app dockerfile
  app:
    build: .
    depends_on:
      - world-db # ensures that database is started before starting app

  # links to database dockerfile
  world-db:
    build: world-db/.
    command: --default-authentication-plugin=mysql_native_password
    restart: always